name: our first Github Action
on:
  push:
    branches:
      - main

jobs:
  first-job:
    name: first job for Github Action Push 
    runs-on: ubuntu-latest
    
    steps:
      - name: list directory before installing checkout 
        run: ls -la  
      - name: Repository Checkout 
        uses: actions/checkout@v4.3.1
      - name: list directory after installing checkout 
        run: ls -la 
