name: manual workflow .
on:
  workflow_dispatch:
    inputs:
      environment:
        description: what environment do you want to trigger this workflow on ? 
        required: true
        default: Staging
        options:
          - Testing
          - Production
          - Staging 
      
jobs:
  simulate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: simulate deploy
        run: echo "deploy running on ${{inputs.environment}}"
